### ISSUE TITLE
Limit set of allowed lecture durations in CfP

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#608] opened 2019-10-25 11:26 UTC
We're receiving a lot of submissions with impossible lecture durations, just because the dropdown allows it and people feel like they need to properly fit the length.

It would be cool to have a way of limiting what the user is presented with in the original CfP interface, even though the edit event view should offer to change duration later to the whole list of durations.

**Comment by eladeyal-intel** [comment] 2019-10-25 12:02
How about this:
 
![image](https://user-images.githubusercontent.com/20379005/67569755-64a0cd80-f738-11e9-8128-7e15e47380fb.png)

**Comment by erdgeist** [comment] 2019-10-25 12:16
Well, we actually need to provide some options, because e.g. at 36C3 we offer 40 and 60 minute lecture lengths, as well as longer slots for games and DJ sets and entertainment. I'd just love to de-select the 10, 20, 30, 50, 70, 80, 100 … as options so that the submitter can't pick wrong ones when initially creating their lectures.

**Comment by eladeyal-intel** [comment] 2019-10-25 13:00
How about this.

![image](https://user-images.githubusercontent.com/20379005/67572977-f8c26300-f73f-11e9-95a0-3ffd950f0161.png)

When migrating, we will auto-populate this field with the default, based on the max duration and the time slot configuration. But for new conferences, this will default to blank. I'm taking the assumption here that nobody wants an arbitrary long duration list, and that conference crew will be content with setting the list themselves.

**Comment by eladeyal-intel** [comment] 2019-10-27 07:55
actually I can use javascript to dynamically add & remove checkboxes for optional durations.

**Comment by erdgeist** [comment] 2019-10-28 15:24
I also thought that … because conferences have time slots and there's a maximal timeslot configuration, we could just add a set of checkboxes that are selected by default, representing timeslots that are shown in the "Create Event" interface. This should be 5 rows of 10 checkboxes for 10 minute slots and 500 minutes max duration. I wonder how acceptable this is UX-wise.

**Comment by eladeyal-intel** [comment] 2019-11-16 16:01
I have the conference settings ready.

The "default duration" is always checked and disabled (un-clickable)

![image](https://user-images.githubusercontent.com/20379005/68995840-e0ef8200-089a-11ea-848a-9409355b8dce.png)

**Comment by eladeyal-intel** [comment] 2019-11-23 17:23
duplicate of #304

**Comment by eladeyal-intel** [comment] 2020-07-25 15:08
#651 is merged - this issue should be closed.

**Closed** 2020-09-19 10:35 UTC
Labels: wish
