### ISSUE TITLE
Configure event type per conference

### ISSUE THREAD

**Issue by herrurbach** [frab/frab#348] opened 2017-09-27 18:24 UTC
It would be great if there is a possibility to set the tracktype per conference

**Comment by manno** [comment] 2017-09-27 19:04
What do you mean by track type?

**Comment by herrurbach** [comment] 2017-09-27 19:35
My bad. I just mixed track (which you can already set) with event type. 

It would be great to choose which kind of event can be a in a conference

I edited the titel.

**Comment by manno** [comment] 2017-10-05 07:04
I think it's a duplicate of #302  now

**Closed by manno** 2017-10-05 07:04 UTC
